name: VisualEyesMedia
favicon: null
layout_spectrum: 0.39248
typography_spectrum: 0.27564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#404040'
    - '#ffffff'
    - '#7f9200'
    - '#6d6d6d'
    - '#a9a9a9'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
