name: VisualEyesMedia
favicon: null
layout_spectrum: 0.5460700546391308
typography_spectrum: 0.15168629679828882
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3128114447463304
  lightness: 0.7510082258377224
  saturation: 0.7228361133020371
  rhythmicContrast: 0.7347519171889871
purpose: []
