name: VisualEyesMedia
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32675
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#404040'
    - '#ffffff'
    - '#7f9200'
    - '#6d6d6d'
    - '#a9a9a9'
  brandStrength: 0.0625
  lightness: 0.7510082258377224
  saturation: 0.7228361133020371
  rhythmicContrast: 0.7347519171889871
purpose: []
