name: VisualEyesMedia
favicon: null
layout_spectrum: 0.30309
typography_spectrum: 0.27564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#404040'
    - '#ffffff'
    - '#7f9200'
    - '#6d6d6d'
    - '#a9a9a9'
  brandStrength: 0.3125
  lightness: 0.3125
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
